# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server


from __future__ import annotations

from typing import Any, Self

from pydantic import ConfigDict, Field, StrictStr

from training_service.contract import ContractModel


class AlgorithmSpec(ContractModel):
    """API contract model.

    Schema: AlgorithmSpec in docs/api/openapi.yaml.
    """

    name: StrictStr = Field(
        description=(
            "Algorithm identifier exposed by GET /algorithms for the configured "
            "Ray Universal Image and release. Use that catalog and its parameter "
            "schema. "
        ),
        json_schema_extra={"examples": ["lora_sft"]},
    )
    parameters: dict[str, Any] | None = Field(
        default=None,
        description=(
            "Optional hyperparameter overrides validated against the selected "
            "algorithm's Training Hub parameter schema. Basic lora_sft overrides "
            "include learning_rate, num_epochs, effective_batch_size (total "
            "samples per optimizer update across GPUs and gradient accumulation), "
            "and max_seq_len (maximum tokens per training sample). These are "
            "optional overrides; example values are not API defaults. Omitted "
            "parameters use the configured backend's defaults. "
        ),
        json_schema_extra={
            "examples": [
                {
                    "learning_rate": 2.0e-5,
                    "num_epochs": 3,
                    "effective_batch_size": 8,
                    "max_seq_len": 2048,
                }
            ]
        },
    )

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        extra="forbid",
    )

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump(mode="json", by_alias=True, exclude_unset=True)

    def to_json(self) -> str:
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_dict(cls, obj: dict[str, Any]) -> Self:
        return cls.model_validate(obj)

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        return cls.model_validate_json(json_str)
