# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server


from __future__ import annotations

from typing import Any, Self

from pydantic import ConfigDict, Field, StrictStr, field_validator

from training_service.contract import ContractModel


class AlgorithmDescriptor(ContractModel):
    """API contract model.

    Schema: AlgorithmDescriptor in docs/api/openapi.yaml.
    """

    name: StrictStr = Field(json_schema_extra={"examples": ["lora_sft"]})
    description: StrictStr | None = Field(
        default=None, json_schema_extra={"examples": ["Low-Rank Adaptation Supervised Fine-Tuning"]}
    )
    supported_backends: list[StrictStr] = Field(json_schema_extra={"examples": [["ray"]]})
    parameter_schema: dict[str, Any] = Field(
        description=(
            "JSON Schema for parameters accepted by this algorithm in the configured image."
        )
    )

    @field_validator("supported_backends")
    def supported_backends_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in ("ray",):
                raise ValueError("each list item must be one of ('ray')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        extra="allow",
    )

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump(mode="json", by_alias=True, exclude_unset=True)

    def to_json(self) -> str:
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_dict(cls, obj: dict[str, Any]) -> Self:
        return cls.model_validate(obj)

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        return cls.model_validate_json(json_str)
