# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server


from __future__ import annotations

import re
from typing import Annotated, Any, Self

from pydantic import ConfigDict, Field, StrictStr, field_validator

from training_service.contract import ContractModel
from training_service_api.models.algorithm_spec import AlgorithmSpec
from training_service_api.models.dataset_spec import DatasetSpec
from training_service_api.models.job_backend import JobBackend
from training_service_api.models.model_spec import ModelSpec
from training_service_api.models.output_spec import OutputSpec
from training_service_api.models.resource_spec import ResourceSpec


class CreateJobRequest(ContractModel):
    """API contract model.

    Schema: CreateJobRequest in docs/api/openapi.yaml.
    """

    name: Annotated[str, Field(min_length=1, strict=True, max_length=47)] = Field(
        description=(
            "DNS-1035-compatible RayJob name; limited to 47 characters by the submission path."
        ),
        json_schema_extra={"examples": ["llama3-8b-alpaca-lora"]},
    )
    queue_name: StrictStr | None = Field(
        default=None,
        description=(
            "Optional Kueue LocalQueue in the target project. When omitted, "
            "CodeFlare uses a configured default LocalQueue if one exists; "
            "otherwise the job is submitted without a queue. Subject to caller "
            "permissions and platform admission policy; this does not grant "
            "access. "
        ),
        json_schema_extra={"examples": ["team-alpha-local-queue"]},
    )
    backend: JobBackend | None = JobBackend.RAY
    model: ModelSpec
    dataset: DatasetSpec
    algorithm: AlgorithmSpec
    resources: ResourceSpec | None = None
    output: OutputSpec | None = None

    @field_validator("name")
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-z]([-a-z0-9]*[a-z0-9])?$", value):
            raise ValueError(r"must validate the regular expression /^[a-z]([-a-z0-9]*[a-z0-9])?$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        extra="forbid",
    )

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump(mode="json", by_alias=True, exclude_unset=True)

    def to_json(self) -> str:
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_dict(cls, obj: dict[str, Any]) -> Self:
        return cls.model_validate(obj)

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        return cls.model_validate_json(json_str)
