# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server


from __future__ import annotations

from typing import Any, Self

from pydantic import ConfigDict, Field, StrictStr, field_validator

from training_service.contract import ContractModel


class ErrorResponse(ContractModel):
    """API contract model.

    Schema: ErrorResponse in docs/api/openapi.yaml.
    """

    code: StrictStr = Field(json_schema_extra={"examples": ["forbidden"]})
    message: StrictStr = Field(
        json_schema_extra={
            "examples": [
                ("Caller is not authorized to perform this operation in project team-alpha-ml.")
            ]
        }
    )
    details: dict[str, Any] | None = Field(
        default=None,
        description=(
            "Optional structured context, such as invalid fields; never includes credentials."
        ),
    )

    @field_validator("code")
    def code_validate_enum(cls, value):
        """Validates the enum"""
        if value not in (
            "bad_request",
            "unauthorized",
            "forbidden",
            "not_found",
            "already_exists",
            "job_not_terminal",
            "logs_not_ready",
            "ray_cluster_gone",
            "unsupported_media_type",
            "validation_error",
            "not_implemented",
        ):
            raise ValueError(
                "must be one of enum values ('bad_request', 'unauthorized', "
                "'forbidden', 'not_found', 'already_exists', 'job_not_terminal', "
                "'logs_not_ready', 'ray_cluster_gone', 'unsupported_media_type', "
                "'validation_error', 'not_implemented')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        extra="forbid",
    )

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump(mode="json", by_alias=True, exclude_unset=True)

    def to_json(self) -> str:
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_dict(cls, obj: dict[str, Any]) -> Self:
        return cls.model_validate(obj)

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        return cls.model_validate_json(json_str)
