# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server


from __future__ import annotations

from typing import Any, Self

from pydantic import ConfigDict, Field, StrictStr, field_validator

from training_service.contract import ContractModel


class EstimationModelSpec(ContractModel):
    """API contract model.

    Schema: EstimationModelSpec in docs/api/openapi.yaml.
    """

    source: StrictStr
    uri: StrictStr = Field(
        description=(
            "Public Hugging Face model ID or a model available to the profiler "
            "without a caller Secret."
        ),
        json_schema_extra={"examples": ["meta-llama/Llama-3.2-3B"]},
    )

    @field_validator("source")
    def source_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ("huggingface",):
            raise ValueError("must be one of enum values ('huggingface')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        extra="forbid",
    )

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump(mode="json", by_alias=True, exclude_unset=True)

    def to_json(self) -> str:
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_dict(cls, obj: dict[str, Any]) -> Self:
        return cls.model_validate(obj)

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        return cls.model_validate_json(json_str)
