# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server

"""Credential interface placeholder; authentication is implemented separately."""

from pydantic import BaseModel


class TokenModel(BaseModel):
    """Reserved for the handwritten authentication implementation."""
