# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server


from __future__ import annotations

import json
from enum import Enum
from typing import Self


class JobStatus(str, Enum):
    """API contract enum.

    Schema: JobStatus in docs/api/openapi.yaml.
    """

    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    STOPPED = "STOPPED"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Parse a JSON enum value."""
        return cls(json.loads(json_str))
