# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server


from __future__ import annotations

from typing import Annotated, Any, Self

from pydantic import ConfigDict, Field

from training_service.contract import ContractModel


class JobEstimationResponseGpuMemoryBytesPerDevice(ContractModel):
    """API contract model.

    Schema: JobEstimationResponseGpuMemoryBytesPerDevice in docs/api/openapi.yaml.
    """

    lower_bound: Annotated[int, Field(strict=True, ge=0)]
    expected: Annotated[int, Field(strict=True, ge=0)]
    upper_bound: Annotated[int, Field(strict=True, ge=0)]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        extra="allow",
    )

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump(mode="json", by_alias=True, exclude_unset=True)

    def to_json(self) -> str:
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_dict(cls, obj: dict[str, Any]) -> Self:
        return cls.model_validate(obj)

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        return cls.model_validate_json(json_str)
