# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server


from __future__ import annotations

from typing import Any, Self

from pydantic import ConfigDict

from training_service.contract import ContractModel
from training_service_api.models.algorithm_spec import AlgorithmSpec
from training_service_api.models.estimation_dataset_spec import EstimationDatasetSpec
from training_service_api.models.estimation_model_spec import EstimationModelSpec
from training_service_api.models.resource_spec import ResourceSpec


class JobEstimationRequest(ContractModel):
    """API contract model.

    Schema: JobEstimationRequest in docs/api/openapi.yaml.
    """

    model: EstimationModelSpec
    dataset: EstimationDatasetSpec
    algorithm: AlgorithmSpec
    resources: ResourceSpec | None = None

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        extra="forbid",
    )

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump(mode="json", by_alias=True, exclude_unset=True)

    def to_json(self) -> str:
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_dict(cls, obj: dict[str, Any]) -> Self:
        return cls.model_validate(obj)

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        return cls.model_validate_json(json_str)
