# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server


from __future__ import annotations

from typing import Annotated, Any, Self

from pydantic import ConfigDict, Field, StrictStr

from training_service.contract import ContractModel
from training_service_api.models.training_job_summary import TrainingJobSummary


class ListTrainingJobs200Response(ContractModel):
    """API contract model.

    Schema: ListTrainingJobs200Response in docs/api/openapi.yaml.
    """

    items: list[TrainingJobSummary]
    total_count: Annotated[int, Field(strict=True, ge=0)] = Field(
        description=(
            "Exact number of caller-readable jobs matching the supplied filters "
            "across all pages before pagination, not the page length or the number "
            "of remaining jobs. With no filters, counts all caller-readable jobs "
            "in the project. Reflects the current request and may change between "
            "requests. "
        )
    )
    next_page_token: StrictStr | None = Field(
        default=None, description="Omitted when no further results are available."
    )

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        extra="allow",
    )

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump(mode="json", by_alias=True, exclude_unset=True)

    def to_json(self) -> str:
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_dict(cls, obj: dict[str, Any]) -> Self:
        return cls.model_validate(obj)

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        return cls.model_validate_json(json_str)
