# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server


from __future__ import annotations

from typing import Any, Self

from pydantic import ConfigDict, Field, StrictBool

from training_service.contract import ContractModel
from training_service_api.models.queue_info import QueueInfo


class QueueInfoResponse(ContractModel):
    """API contract model.

    Schema: QueueInfoResponse in docs/api/openapi.yaml.
    """

    kueue_enabled: StrictBool = Field(
        description="False when Kueue is absent or disabled in the target deployment."
    )
    queues: list[QueueInfo]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        extra="allow",
    )

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump(mode="json", by_alias=True, exclude_unset=True)

    def to_json(self) -> str:
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_dict(cls, obj: dict[str, Any]) -> Self:
        return cls.model_validate(obj)

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        return cls.model_validate_json(json_str)
