# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server


from __future__ import annotations

from typing import Annotated, Any, Self

from pydantic import ConfigDict, Field, StrictStr

from training_service.contract import ContractModel


class ResourceSpec(ContractModel):
    """API contract model.

    Schema: ResourceSpec in docs/api/openapi.yaml.
    """

    num_nodes: Annotated[int, Field(strict=True, ge=1)] | None = Field(
        default=1, json_schema_extra={"examples": [2]}
    )
    gpus_per_node: Annotated[int, Field(strict=True, ge=0)] | None = Field(
        default=1, json_schema_extra={"examples": [4]}
    )
    gpu_type: StrictStr | None = Field(
        default=None, json_schema_extra={"examples": ["nvidia.com/gpu"]}
    )
    cpus_per_node: StrictStr | None = Field(default="8", json_schema_extra={"examples": ["16"]})
    memory_per_node: StrictStr | None = Field(
        default="32Gi", json_schema_extra={"examples": ["64Gi"]}
    )

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        extra="forbid",
    )

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump(mode="json", by_alias=True, exclude_unset=True)

    def to_json(self) -> str:
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_dict(cls, obj: dict[str, Any]) -> Self:
        return cls.model_validate(obj)

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        return cls.model_validate_json(json_str)
