# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server


from __future__ import annotations

from typing import Any, Self

from pydantic import ConfigDict, Field, StrictFloat, StrictInt

from training_service.contract import ContractModel


class TrainingJobProgress(ContractModel):
    """API contract model.

    Schema: TrainingJobProgress in docs/api/openapi.yaml.
    """

    percentage: StrictFloat | StrictInt | None = Field(
        default=None, json_schema_extra={"examples": [45.5]}
    )
    current_epoch: StrictInt | None = Field(default=None, json_schema_extra={"examples": [2]})
    total_epochs: StrictInt | None = Field(default=None, json_schema_extra={"examples": [5]})
    current_step: StrictInt | None = Field(default=None, json_schema_extra={"examples": [910]})
    total_steps: StrictInt | None = Field(default=None, json_schema_extra={"examples": [2000]})
    eta_seconds: StrictInt | None = Field(default=None, json_schema_extra={"examples": [1240]})

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        extra="allow",
    )

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump(mode="json", by_alias=True, exclude_unset=True)

    def to_json(self) -> str:
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_dict(cls, obj: dict[str, Any]) -> Self:
        return cls.model_validate(obj)

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        return cls.model_validate_json(json_str)
