# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server


from __future__ import annotations

from typing import Any, Self

from pydantic import ConfigDict, Field, StrictStr, field_validator

from training_service.contract import ContractModel


class TrainingJobSubmission(ContractModel):
    """API contract model.

    Schema: TrainingJobSubmission in docs/api/openapi.yaml.
    """

    id: StrictStr = Field(
        description="Name of the created RayJob custom resource.",
        json_schema_extra={"examples": ["llama3-8b-alpaca-lora"]},
    )
    name: StrictStr = Field(json_schema_extra={"examples": ["llama3-8b-alpaca-lora"]})
    project: StrictStr = Field(json_schema_extra={"examples": ["team-alpha-ml"]})
    queue_name: StrictStr | None = Field(
        default=None, json_schema_extra={"examples": ["team-alpha-local-queue"]}
    )
    status: StrictStr = Field(
        description="Submission acknowledgement only; not a lifecycle status."
    )
    selected_backend: StrictStr

    @field_validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ("SUBMITTED",):
            raise ValueError("must be one of enum values ('SUBMITTED')")
        return value

    @field_validator("selected_backend")
    def selected_backend_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ("ray",):
            raise ValueError("must be one of enum values ('ray')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        extra="allow",
    )

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump(mode="json", by_alias=True, exclude_unset=True)

    def to_json(self) -> str:
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_dict(cls, obj: dict[str, Any]) -> Self:
        return cls.model_validate(obj)

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        return cls.model_validate_json(json_str)
