# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server


from __future__ import annotations

from datetime import datetime
from typing import Any, Self

from pydantic import (
    ConfigDict,
    Field,
    StrictFloat,
    StrictInt,
    StrictStr,
    field_validator,
)

from training_service.contract import ContractModel
from training_service_api.models.create_job_request import CreateJobRequest
from training_service_api.models.job_status import JobStatus
from training_service_api.models.resource_spec import ResourceSpec
from training_service_api.models.training_job_progress import TrainingJobProgress


class TrainingJob(ContractModel):
    """API contract model.

    Schema: TrainingJob in docs/api/openapi.yaml.
    """

    id: StrictStr = Field(
        description="Name of the RayJob custom resource in the project.",
        json_schema_extra={"examples": ["llama3-8b-alpaca-lora"]},
    )
    name: StrictStr | None = Field(
        default=None, json_schema_extra={"examples": ["llama3-8b-alpaca-lora"]}
    )
    project: StrictStr = Field(json_schema_extra={"examples": ["team-alpha-ml"]})
    submitted_by: StrictStr | None = Field(
        default=None,
        description=(
            "Original submitter's OpenShift username, resolved from the "
            "authenticated submission token and recorded in the RayJob annotation "
            "training.rhoai.io/submitted-by. May be a human username or a service "
            "account identity such as "
            "system:serviceaccount:team-alpha-ml:training-client. Never supplied "
            "by a client or inferred from the caller reading the job. Omitted when "
            "the annotation is absent. Informational attribution only, not "
            "tamper-proof audit evidence and never used for authorization. "
        ),
        json_schema_extra={"examples": ["alice"]},
    )
    submission: CreateJobRequest | None = Field(
        default=None,
        description=(
            "Accepted POST payload retained for API-created jobs in "
            "caller-authorized RayJob metadata. Preserves submitted values, "
            "including model, dataset, algorithm parameters, and any supplied "
            "queue, backend, resources, or output settings. Optional fields and "
            "nested defaults that were not supplied remain absent; this is not the "
            "effective runtime configuration. Omitted for external or older jobs "
            "without recorded submission metadata; never reconstructed from "
            "command-line arguments or raw runtime environments. Storage URIs "
            "contain project-local Secret, connection, or PVC names only, never "
            "credentials or Secret contents. "
        ),
    )
    queue_name: StrictStr | None = Field(
        default=None, json_schema_extra={"examples": ["team-alpha-local-queue"]}
    )
    status: JobStatus
    selected_backend: StrictStr = Field(json_schema_extra={"examples": ["ray"]})
    progress: TrainingJobProgress | None = None
    metrics: dict[str, StrictFloat | StrictInt] | None = Field(
        default=None,
        description="Optional training metrics, only when reported by an authorized source.",
        json_schema_extra={
            "examples": [
                {
                    "loss": 0.184,
                    "eval_loss": 0.212,
                    "learning_rate": 1.5e-4,
                    "throughput_tokens_per_sec": 1420.5,
                }
            ]
        },
    )
    resources: ResourceSpec | None = Field(
        default=None,
        description=(
            "Runtime resource configuration from an authorized source, when "
            "available. Do not infer it solely from requested resources; "
            "submission.resources preserves the submitted settings separately. "
        ),
    )
    created_at: datetime | None = Field(
        default=None,
        description=(
            "RayJob resource creation timestamp from Kubernetes "
            "metadata.creationTimestamp, in RFC 3339 format, including for "
            "externally created jobs. Distinct from the training start time "
            "reported in started_at. "
        ),
    )
    started_at: datetime | None = Field(
        default=None,
        description="Ray start timestamp converted from Unix milliseconds to RFC 3339.",
    )
    finished_at: datetime | None = Field(
        default=None,
        description=(
            "Ray execution end timestamp in RFC 3339 format, when reported for a "
            "terminal SUCCEEDED, FAILED, or STOPPED job. Omitted while pending or "
            "running, or when Ray has not reported an end time. Never inferred "
            "from the current time or resource creation time. "
        ),
    )
    failure_reason: StrictStr | None = Field(
        default=None, description="Ray failure message when status is FAILED, if available."
    )

    @field_validator("selected_backend")
    def selected_backend_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ("ray",):
            raise ValueError("must be one of enum values ('ray')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        extra="allow",
    )

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump(mode="json", by_alias=True, exclude_unset=True)

    def to_json(self) -> str:
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_dict(cls, obj: dict[str, Any]) -> Self:
        return cls.model_validate(obj)

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        return cls.model_validate_json(json_str)
