# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server


from __future__ import annotations

from datetime import datetime
from typing import Any, Self

from pydantic import ConfigDict, Field, StrictStr

from training_service.contract import ContractModel
from training_service_api.models.job_status import JobStatus


class TrainingJobSummary(ContractModel):
    """API contract model.

    Schema: TrainingJobSummary in docs/api/openapi.yaml.
    """

    id: StrictStr = Field(
        description="Name of the RayJob custom resource in the requested project.",
        json_schema_extra={"examples": ["llama3-8b-alpaca-lora"]},
    )
    status: JobStatus
    queue_name: StrictStr | None = Field(
        default=None,
        description=("Kueue LocalQueue recorded in training submission metadata, when available."),
        json_schema_extra={"examples": ["team-alpha-local-queue"]},
    )
    created_at: datetime = Field(
        description=(
            "RayJob resource creation timestamp from Kubernetes "
            "metadata.creationTimestamp, in RFC 3339 format. Present for all "
            "persisted RayJobs, including externally created jobs; not the "
            "training start time. "
        )
    )

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        extra="forbid",
    )

    def to_dict(self) -> dict[str, Any]:
        return self.model_dump(mode="json", by_alias=True, exclude_unset=True)

    def to_json(self) -> str:
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_dict(cls, obj: dict[str, Any]) -> Self:
        return cls.model_validate(obj)

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        return cls.model_validate_json(json_str)
