# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server

"""Fail-closed authentication extension point for the generated scaffold."""

from training_service.errors import ApiError
from training_service_api.models.extra_models import TokenModel


async def get_token_OpenShiftBearer() -> TokenModel:
    """Do not authenticate callers or allow backend access in this scaffold."""
    raise ApiError(501, "not_implemented", "OpenShift authentication is not implemented.")
