"""Wrap generated string literals without changing their runtime values.

Ruff formats Python syntax, but deliberately leaves long prose strings intact.
Split those literals into adjacent strings before Ruff runs. An AST comparison
rejects any edit that would change the generated program's semantics.
"""

import argparse
import ast
import io
import tokenize
from collections.abc import Iterator
from pathlib import Path

GENERATED_HEADER = (
    "# Generated by OpenAPI Generator from docs/api/openapi.yaml.\n"
    "# DO NOT EDIT. Change the contract/templates and regenerate instead.\n"
    "# Regenerate with: make generate-server\n"
)


def literal_parts(value: str, width: int = 72) -> Iterator[str]:
    """Yield exact string fragments, including all original whitespace."""
    while value:
        end = min(len(value), width - 2)
        while len(repr(value[:end])) > width:
            end -= 1
        if end < len(value):
            space = value.rfind(" ", 0, end)
            if space > 0:
                end = space + 1
        yield repr(value[:end])
        value = value[end:]


def wrap_literals(source: str, line_length: int = 100) -> str:
    """Wrap long single-line literals; templates own concise docstrings."""
    lines = source.splitlines(keepends=True)
    offsets = [0]
    for line in lines:
        offsets.append(offsets[-1] + len(line))
    edits: list[tuple[int, int, str]] = []
    for token in tokenize.generate_tokens(io.StringIO(source).readline):
        row, column = token.start
        if (
            token.type != tokenize.STRING
            or row != token.end[0]
            or len(lines[row - 1].rstrip("\n")) <= line_length
            or token.string[:3] in ('"' * 3, "'" * 3)
        ):
            continue
        value = ast.literal_eval(token.string)
        if not isinstance(value, str) or len(repr(value)) <= 72:
            continue
        line = lines[row - 1]
        indent = line[: len(line) - len(line.lstrip())]
        parts = "\n".join(indent + "    " + part for part in literal_parts(value))
        replacement = "(\n" + parts + "\n" + indent + ")"
        start = offsets[row - 1] + column
        end = offsets[token.end[0] - 1] + token.end[1]
        edits.append((start, end, replacement))
    result = source
    for start, end, replacement in reversed(edits):
        result = result[:start] + replacement + result[end:]
    if ast.dump(ast.parse(source)) != ast.dump(ast.parse(result)):
        raise ValueError("String wrapping changed the generated program's AST")
    return result


def format_source(source: str) -> str:
    """Preserve behavior and identify every file as generated, including markers."""
    if not source.strip() or source.strip() == GENERATED_HEADER.strip():
        return GENERATED_HEADER
    result = wrap_literals(source)
    if GENERATED_HEADER not in result:
        result = GENERATED_HEADER + "\n" + result
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("directory", type=Path)
    directory = parser.parse_args().directory
    package_init = directory / "__init__.py"
    if not package_init.exists():
        package_init.write_text(GENERATED_HEADER, encoding="utf-8")
    for path in sorted(directory.rglob("*.py")):
        source = path.read_text(encoding="utf-8")
        result = format_source(source)
        if result != source:
            path.write_text(result, encoding="utf-8")


if __name__ == "__main__":
    main()
