"""Minimal regression proof for the generator's prose-wrapping step."""

import ast
import runpy
from pathlib import Path


def test_literal_wrapping_preserves_values_and_is_repeatable() -> None:
    formatter = Path(__file__).parents[2] / "docs" / "api" / "format_generated.py"
    formatting = runpy.run_path(str(formatter))
    format_source = formatting["format_source"]
    assert format_source("") == formatting["GENERATED_HEADER"]
    values = [
        "Caller permissions and project isolation. " * 10,
        "Quotes: ' and \"; backslash: \\; newline: \n; tab: \t. " * 10,
        "Unicode: naïve café — permissions. " * 10,
        "longword" * 50,
    ]
    for value in values:
        source = "description = " + repr(value) + "\n"
        wrapped = format_source(source)
        assert ast.dump(ast.parse(wrapped)) == ast.dump(ast.parse(source))
        assert format_source(wrapped) == wrapped
        assert formatting["GENERATED_HEADER"] in wrapped
        assert all(len(line) <= 100 for line in wrapped.splitlines())


def test_api_package_files_are_marked_generated() -> None:
    package = Path(__file__).parents[2] / "src" / "training_service_api"
    sources = list(package.rglob("*.py"))
    assert sources
    for source in sources:
        header = "\n".join(source.read_text(encoding="utf-8").splitlines()[:5])
        assert "Generated by OpenAPI Generator" in header, source
        assert "DO NOT EDIT" in header, source
        assert "make generate-server" in header, source
