# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server

import importlib
import pkgutil

from fastapi import (
    APIRouter,
    Body,
    Security,
)

import training_service_api.impl
from training_service.errors import ApiError
from training_service_api.apis.estimations_api_base import BaseEstimationsApi
from training_service_api.models.error_response import ErrorResponse
from training_service_api.models.extra_models import TokenModel
from training_service_api.models.job_estimation_request import JobEstimationRequest
from training_service_api.models.job_estimation_response import JobEstimationResponse
from training_service_api.security_api import get_token_OpenShiftBearer

router = APIRouter()

ns_pkg = training_service_api.impl
for _, name, _ in pkgutil.iter_modules(ns_pkg.__path__, ns_pkg.__name__ + "."):
    importlib.import_module(name)


@router.post(
    "/training-jobs/estimate",
    responses={
        200: {
            "model": JobEstimationResponse,
            "description": "Synchronous GPU-memory estimate and, when supported, a timing range",
        },
        400: {
            "model": ErrorResponse,
            "description": "Malformed JSON or invalid query/path parameter syntax",
        },
        401: {
            "model": ErrorResponse,
            "description": "Missing, invalid, or expired OpenShift bearer token",
        },
        415: {"model": ErrorResponse, "description": "Request body must use application/json"},
        422: {
            "model": ErrorResponse,
            "description": "JSON is well-formed but fails schema or domain validation",
        },
    },
    tags=["Estimations"],
    summary="Estimate training resources (stretch goal)",
    response_model_by_alias=True,
    response_model_exclude_unset=True,
)
async def estimate_training_job(
    job_estimation_request: JobEstimationRequest = Body(..., description=""),
    token_OpenShiftBearer: TokenModel = Security(get_token_OpenShiftBearer),
) -> JobEstimationResponse:
    """Estimate training resources (stretch goal)"""
    if not BaseEstimationsApi.subclasses:
        raise ApiError(501, "not_implemented", "This operation is not implemented in the scaffold.")
    return await BaseEstimationsApi.subclasses[0]().estimate_training_job(
        job_estimation_request,
        token_OpenShiftBearer=token_OpenShiftBearer,
    )
