# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server

from typing import ClassVar

from training_service_api.models.extra_models import TokenModel
from training_service_api.models.job_estimation_request import JobEstimationRequest
from training_service_api.models.job_estimation_response import JobEstimationResponse


class BaseEstimationsApi:
    subclasses: ClassVar[tuple] = ()

    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        BaseEstimationsApi.subclasses = BaseEstimationsApi.subclasses + (cls,)

    async def estimate_training_job(
        self,
        job_estimation_request: JobEstimationRequest,
        token_OpenShiftBearer: TokenModel,
    ) -> JobEstimationResponse:
        """Estimate training resources (stretch goal)"""
        ...
