# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server

from typing import Annotated, ClassVar

from pydantic import Field, StrictStr

from training_service_api.models.extra_models import TokenModel
from training_service_api.models.list_algorithms200_response import ListAlgorithms200Response
from training_service_api.models.queue_info_response import QueueInfoResponse


class BaseInfrastructureDiscoveryApi:
    subclasses: ClassVar[tuple] = ()

    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        BaseInfrastructureDiscoveryApi.subclasses = BaseInfrastructureDiscoveryApi.subclasses + (
            cls,
        )

    async def list_algorithms(
        self,
        token_OpenShiftBearer: TokenModel,
    ) -> ListAlgorithms200Response:
        """List available Ray training algorithms"""
        ...

    async def list_queues(
        self,
        project: Annotated[
            StrictStr,
            Field(
                description=(
                    "Explicit pre-existing OpenShift Project (Kubernetes namespace); all "
                    "resource references are scoped to it. Provision the project through "
                    "normal OpenShift self-service or administrator workflows before using "
                    "this API. The Training API does not create projects or namespaces and "
                    "never falls back to a default namespace or an elevated service "
                    "identity. A missing project returns 404; insufficient caller "
                    "permissions return 403. "
                )
            ),
        ],
        token_OpenShiftBearer: TokenModel,
    ) -> QueueInfoResponse:
        """List available Kueue LocalQueues in the OpenShift Project (if Kueue is enabled)"""
        ...
