# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server

import importlib
import pkgutil
from typing import Annotated

from fastapi import (
    APIRouter,
    Path,
    Security,
)
from pydantic import Field, StrictStr

import training_service_api.impl
from training_service.errors import ApiError
from training_service_api.apis.infrastructure_discovery_api_base import (
    BaseInfrastructureDiscoveryApi,
)
from training_service_api.models.error_response import ErrorResponse
from training_service_api.models.extra_models import TokenModel
from training_service_api.models.list_algorithms200_response import ListAlgorithms200Response
from training_service_api.models.queue_info_response import QueueInfoResponse
from training_service_api.security_api import get_token_OpenShiftBearer

router = APIRouter()

ns_pkg = training_service_api.impl
for _, name, _ in pkgutil.iter_modules(ns_pkg.__path__, ns_pkg.__name__ + "."):
    importlib.import_module(name)


@router.get(
    "/algorithms",
    responses={
        200: {
            "model": ListAlgorithms200Response,
            "description": (
                "Configured-image catalog of available algorithms and hyperparameter schemas"
            ),
        },
        401: {
            "model": ErrorResponse,
            "description": "Missing, invalid, or expired OpenShift bearer token",
        },
        403: {
            "model": ErrorResponse,
            "description": (
                "User lacks OpenShift RBAC permissions for the requested resource or project"
            ),
        },
    },
    tags=["Infrastructure &amp; Discovery"],
    summary="List available Ray training algorithms",
    response_model_by_alias=True,
    response_model_exclude_unset=True,
)
async def list_algorithms(
    token_OpenShiftBearer: TokenModel = Security(get_token_OpenShiftBearer),
) -> ListAlgorithms200Response:
    """List available Ray training algorithms"""
    if not BaseInfrastructureDiscoveryApi.subclasses:
        raise ApiError(501, "not_implemented", "This operation is not implemented in the scaffold.")
    return await BaseInfrastructureDiscoveryApi.subclasses[0]().list_algorithms(
        token_OpenShiftBearer=token_OpenShiftBearer,
    )


@router.get(
    "/projects/{project}/queues",
    responses={
        200: {
            "model": QueueInfoResponse,
            "description": "List of LocalQueues accessible in the specified OpenShift Project",
        },
        401: {
            "model": ErrorResponse,
            "description": "Missing, invalid, or expired OpenShift bearer token",
        },
        403: {
            "model": ErrorResponse,
            "description": (
                "User lacks OpenShift RBAC permissions for the requested resource or project"
            ),
        },
        404: {
            "model": ErrorResponse,
            "description": (
                "Target project, RayJob, or referenced project resource does not exist "
                "in the requested scope"
            ),
        },
    },
    tags=["Infrastructure &amp; Discovery"],
    summary="List available Kueue LocalQueues in the OpenShift Project (if Kueue is enabled)",
    response_model_by_alias=True,
    response_model_exclude_unset=True,
)
async def list_queues(
    project: Annotated[
        StrictStr,
        Field(
            description=(
                "Explicit pre-existing OpenShift Project (Kubernetes namespace); all "
                "resource references are scoped to it. Provision the project through "
                "normal OpenShift self-service or administrator workflows before using "
                "this API. The Training API does not create projects or namespaces and "
                "never falls back to a default namespace or an elevated service "
                "identity. A missing project returns 404; insufficient caller "
                "permissions return 403. "
            )
        ),
    ] = Path(
        ...,
        description=(
            "Explicit pre-existing OpenShift Project (Kubernetes namespace); all "
            "resource references are scoped to it. Provision the project through "
            "normal OpenShift self-service or administrator workflows before using "
            "this API. The Training API does not create projects or namespaces and "
            "never falls back to a default namespace or an elevated service "
            "identity. A missing project returns 404; insufficient caller "
            "permissions return 403. "
        ),
        examples=["team-alpha-ml"],
    ),
    token_OpenShiftBearer: TokenModel = Security(get_token_OpenShiftBearer),
) -> QueueInfoResponse:
    """List available Kueue LocalQueues in the OpenShift Project (if Kueue is enabled)"""
    if not BaseInfrastructureDiscoveryApi.subclasses:
        raise ApiError(501, "not_implemented", "This operation is not implemented in the scaffold.")
    return await BaseInfrastructureDiscoveryApi.subclasses[0]().list_queues(
        project,
        token_OpenShiftBearer=token_OpenShiftBearer,
    )
