# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server

import importlib
import pkgutil
from typing import Annotated

from fastapi import (
    APIRouter,
    Path,
    Query,
    Security,
)
from pydantic import Field, StrictBool, StrictStr

import training_service_api.impl
from training_service.errors import ApiError
from training_service_api.apis.observability_api_base import BaseObservabilityApi
from training_service_api.models.error_response import ErrorResponse
from training_service_api.models.extra_models import TokenModel
from training_service_api.security_api import get_token_OpenShiftBearer

router = APIRouter()

ns_pkg = training_service_api.impl
for _, name, _ in pkgutil.iter_modules(ns_pkg.__path__, ns_pkg.__name__ + "."):
    importlib.import_module(name)


@router.get(
    "/projects/{project}/training-jobs/{job_id}/logs",
    responses={
        200: {"model": str, "description": "Driver log snapshot or SSE stream, selected by follow"},
        400: {
            "model": ErrorResponse,
            "description": "Malformed JSON or invalid query/path parameter syntax",
        },
        401: {
            "model": ErrorResponse,
            "description": "Missing, invalid, or expired OpenShift bearer token",
        },
        403: {
            "model": ErrorResponse,
            "description": (
                "User lacks OpenShift RBAC permissions for the requested resource or project"
            ),
        },
        404: {
            "model": ErrorResponse,
            "description": (
                "Target project, RayJob, or referenced project resource does not exist "
                "in the requested scope"
            ),
        },
        409: {
            "model": ErrorResponse,
            "description": "RayJob exists, but driver logs are not ready yet",
        },
        410: {
            "model": ErrorResponse,
            "description": "RayJob exists, but its managed RayCluster and logs are gone",
        },
    },
    tags=["Observability"],
    summary="Read or follow training job driver logs",
    response_model_by_alias=True,
    response_model_exclude_unset=True,
)
async def stream_job_logs(
    project: Annotated[
        StrictStr,
        Field(
            description=(
                "Explicit pre-existing OpenShift Project (Kubernetes namespace); all "
                "resource references are scoped to it. Provision the project through "
                "normal OpenShift self-service or administrator workflows before using "
                "this API. The Training API does not create projects or namespaces and "
                "never falls back to a default namespace or an elevated service "
                "identity. A missing project returns 404; insufficient caller "
                "permissions return 403. "
            )
        ),
    ] = Path(
        ...,
        description=(
            "Explicit pre-existing OpenShift Project (Kubernetes namespace); all "
            "resource references are scoped to it. Provision the project through "
            "normal OpenShift self-service or administrator workflows before using "
            "this API. The Training API does not create projects or namespaces and "
            "never falls back to a default namespace or an elevated service "
            "identity. A missing project returns 404; insufficient caller "
            "permissions return 403. "
        ),
        examples=["team-alpha-ml"],
    ),
    job_id: Annotated[
        StrictStr,
        Field(
            description=(
                "Name of the RayJob custom resource, scoped to the target project. "
                "Resolve it only through caller-authorized Kubernetes APIs in that "
                "project. "
            )
        ),
    ] = Path(
        ...,
        description=(
            "Name of the RayJob custom resource, scoped to the target project. "
            "Resolve it only through caller-authorized Kubernetes APIs in that "
            "project. "
        ),
        examples=["llama3-8b-alpaca-lora"],
    ),
    follow: Annotated[
        StrictBool | None,
        Field(description="False returns text/plain; true follows logs as text/event-stream."),
    ] = Query(
        False,
        description="False returns text/plain; true follows logs as text/event-stream.",
        alias="follow",
    ),
    tail_lines: Annotated[
        Annotated[int, Field(strict=True, ge=1)] | None,
        Field(
            description=(
                "Number of trailing lines in the non-following snapshot, selected by "
                "the service after get_job_logs. Ignored when follow=true, which "
                "forwards the log chunks provided by Ray's tail_job_logs. "
            )
        ),
    ] = Query(
        100,
        description=(
            "Number of trailing lines in the non-following snapshot, selected by "
            "the service after get_job_logs. Ignored when follow&#x3D;true, which "
            "forwards the log chunks provided by Ray&#39;s tail_job_logs. "
        ),
        alias="tail_lines",
        ge=1,
    ),
    token_OpenShiftBearer: TokenModel = Security(get_token_OpenShiftBearer),
) -> str:
    """Read or follow training job driver logs"""
    if not BaseObservabilityApi.subclasses:
        raise ApiError(501, "not_implemented", "This operation is not implemented in the scaffold.")
    return await BaseObservabilityApi.subclasses[0]().stream_job_logs(
        project,
        job_id,
        follow,
        tail_lines,
        token_OpenShiftBearer=token_OpenShiftBearer,
    )
