# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server

from typing import Annotated, ClassVar

from pydantic import Field, StrictBool, StrictStr

from training_service_api.models.extra_models import TokenModel


class BaseObservabilityApi:
    subclasses: ClassVar[tuple] = ()

    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        BaseObservabilityApi.subclasses = BaseObservabilityApi.subclasses + (cls,)

    async def stream_job_logs(
        self,
        project: Annotated[
            StrictStr,
            Field(
                description=(
                    "Explicit pre-existing OpenShift Project (Kubernetes namespace); all "
                    "resource references are scoped to it. Provision the project through "
                    "normal OpenShift self-service or administrator workflows before using "
                    "this API. The Training API does not create projects or namespaces and "
                    "never falls back to a default namespace or an elevated service "
                    "identity. A missing project returns 404; insufficient caller "
                    "permissions return 403. "
                )
            ),
        ],
        job_id: Annotated[
            StrictStr,
            Field(
                description=(
                    "Name of the RayJob custom resource, scoped to the target project. "
                    "Resolve it only through caller-authorized Kubernetes APIs in that "
                    "project. "
                )
            ),
        ],
        follow: Annotated[
            StrictBool | None,
            Field(description="False returns text/plain; true follows logs as text/event-stream."),
        ],
        tail_lines: Annotated[
            Annotated[int, Field(strict=True, ge=1)] | None,
            Field(
                description=(
                    "Number of trailing lines in the non-following snapshot, selected by "
                    "the service after get_job_logs. Ignored when follow=true, which "
                    "forwards the log chunks provided by Ray's tail_job_logs. "
                )
            ),
        ],
        token_OpenShiftBearer: TokenModel,
    ) -> str:
        """Read or follow training job driver logs"""
        ...
