# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server

from typing import Annotated, ClassVar

from pydantic import Field, StrictStr

from training_service_api.models.create_job_request import CreateJobRequest
from training_service_api.models.extra_models import TokenModel
from training_service_api.models.job_status import JobStatus
from training_service_api.models.list_training_jobs200_response import ListTrainingJobs200Response
from training_service_api.models.training_job import TrainingJob
from training_service_api.models.training_job_submission import TrainingJobSubmission


class BaseTrainingJobsApi:
    subclasses: ClassVar[tuple] = ()

    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        BaseTrainingJobsApi.subclasses = BaseTrainingJobsApi.subclasses + (cls,)

    async def list_training_jobs(
        self,
        project: Annotated[
            StrictStr,
            Field(
                description=(
                    "Explicit pre-existing OpenShift Project (Kubernetes namespace); all "
                    "resource references are scoped to it. Provision the project through "
                    "normal OpenShift self-service or administrator workflows before using "
                    "this API. The Training API does not create projects or namespaces and "
                    "never falls back to a default namespace or an elevated service "
                    "identity. A missing project returns 404; insufficient caller "
                    "permissions return 403. "
                )
            ),
        ],
        status: Annotated[
            JobStatus | None,
            Field(
                description=(
                    "Optional exact-status filter. When omitted, includes jobs in all "
                    "statuses, subject to caller access, other filters, and pagination. "
                    "There is no default status filter or ALL status value. "
                )
            ),
        ],
        queue_name: Annotated[
            StrictStr | None,
            Field(description="Filter by queue name recorded in training submission metadata."),
        ],
        limit: Annotated[int, Field(strict=True, ge=1)] | None,
        page_token: Annotated[
            StrictStr | None,
            Field(
                description=(
                    "Opaque continuation token for the same project and filters. The token "
                    "never grants access; every request rechecks caller permissions. "
                )
            ),
        ],
        token_OpenShiftBearer: TokenModel,
    ) -> ListTrainingJobs200Response:
        """List training jobs in an OpenShift Project"""
        ...

    async def create_training_job(
        self,
        project: Annotated[
            StrictStr,
            Field(
                description=(
                    "Explicit pre-existing OpenShift Project (Kubernetes namespace); all "
                    "resource references are scoped to it. Provision the project through "
                    "normal OpenShift self-service or administrator workflows before using "
                    "this API. The Training API does not create projects or namespaces and "
                    "never falls back to a default namespace or an elevated service "
                    "identity. A missing project returns 404; insufficient caller "
                    "permissions return 403. "
                )
            ),
        ],
        create_job_request: CreateJobRequest,
        token_OpenShiftBearer: TokenModel,
    ) -> TrainingJobSubmission:
        """Submit a Ray training job in an OpenShift Project"""
        ...

    async def get_training_job(
        self,
        project: Annotated[
            StrictStr,
            Field(
                description=(
                    "Explicit pre-existing OpenShift Project (Kubernetes namespace); all "
                    "resource references are scoped to it. Provision the project through "
                    "normal OpenShift self-service or administrator workflows before using "
                    "this API. The Training API does not create projects or namespaces and "
                    "never falls back to a default namespace or an elevated service "
                    "identity. A missing project returns 404; insufficient caller "
                    "permissions return 403. "
                )
            ),
        ],
        job_id: Annotated[
            StrictStr,
            Field(
                description=(
                    "Name of the RayJob custom resource, scoped to the target project. "
                    "Resolve it only through caller-authorized Kubernetes APIs in that "
                    "project. "
                )
            ),
        ],
        token_OpenShiftBearer: TokenModel,
    ) -> TrainingJob:
        """Get training job status and available details"""
        ...

    async def delete_training_job(
        self,
        project: Annotated[
            StrictStr,
            Field(
                description=(
                    "Explicit pre-existing OpenShift Project (Kubernetes namespace); all "
                    "resource references are scoped to it. Provision the project through "
                    "normal OpenShift self-service or administrator workflows before using "
                    "this API. The Training API does not create projects or namespaces and "
                    "never falls back to a default namespace or an elevated service "
                    "identity. A missing project returns 404; insufficient caller "
                    "permissions return 403. "
                )
            ),
        ],
        job_id: Annotated[
            StrictStr,
            Field(
                description=(
                    "Name of the RayJob custom resource, scoped to the target project. "
                    "Resolve it only through caller-authorized Kubernetes APIs in that "
                    "project. "
                )
            ),
        ],
        token_OpenShiftBearer: TokenModel,
    ) -> None:
        """Delete a terminal Ray training job record"""
        ...
