# Generated by OpenAPI Generator from docs/api/openapi.yaml.
# DO NOT EDIT. Change the contract/templates and regenerate instead.
# Regenerate with: make generate-server

import importlib
import pkgutil
from typing import Annotated

from fastapi import (
    APIRouter,
    Body,
    Path,
    Query,
    Security,
)
from pydantic import Field, StrictStr

import training_service_api.impl
from training_service.errors import ApiError
from training_service_api.apis.training_jobs_api_base import BaseTrainingJobsApi
from training_service_api.models.create_job_request import CreateJobRequest
from training_service_api.models.error_response import ErrorResponse
from training_service_api.models.extra_models import TokenModel
from training_service_api.models.job_status import JobStatus
from training_service_api.models.list_training_jobs200_response import ListTrainingJobs200Response
from training_service_api.models.training_job import TrainingJob
from training_service_api.models.training_job_submission import TrainingJobSubmission
from training_service_api.security_api import get_token_OpenShiftBearer

router = APIRouter()

ns_pkg = training_service_api.impl
for _, name, _ in pkgutil.iter_modules(ns_pkg.__path__, ns_pkg.__name__ + "."):
    importlib.import_module(name)


@router.get(
    "/projects/{project}/training-jobs",
    responses={
        200: {
            "model": ListTrainingJobs200Response,
            "description": (
                "Compact page of authorized training jobs and total matching count; an "
                "empty result has items empty and total_count zero"
            ),
        },
        400: {
            "model": ErrorResponse,
            "description": "Malformed JSON or invalid query/path parameter syntax",
        },
        401: {
            "model": ErrorResponse,
            "description": "Missing, invalid, or expired OpenShift bearer token",
        },
        403: {
            "model": ErrorResponse,
            "description": (
                "User lacks OpenShift RBAC permissions for the requested resource or project"
            ),
        },
        404: {
            "model": ErrorResponse,
            "description": (
                "Target project, RayJob, or referenced project resource does not exist "
                "in the requested scope"
            ),
        },
    },
    tags=["Training Jobs"],
    summary="List training jobs in an OpenShift Project",
    response_model_by_alias=True,
    response_model_exclude_unset=True,
)
async def list_training_jobs(
    project: Annotated[
        StrictStr,
        Field(
            description=(
                "Explicit pre-existing OpenShift Project (Kubernetes namespace); all "
                "resource references are scoped to it. Provision the project through "
                "normal OpenShift self-service or administrator workflows before using "
                "this API. The Training API does not create projects or namespaces and "
                "never falls back to a default namespace or an elevated service "
                "identity. A missing project returns 404; insufficient caller "
                "permissions return 403. "
            )
        ),
    ] = Path(
        ...,
        description=(
            "Explicit pre-existing OpenShift Project (Kubernetes namespace); all "
            "resource references are scoped to it. Provision the project through "
            "normal OpenShift self-service or administrator workflows before using "
            "this API. The Training API does not create projects or namespaces and "
            "never falls back to a default namespace or an elevated service "
            "identity. A missing project returns 404; insufficient caller "
            "permissions return 403. "
        ),
        examples=["team-alpha-ml"],
    ),
    status: Annotated[
        JobStatus | None,
        Field(
            description=(
                "Optional exact-status filter. When omitted, includes jobs in all "
                "statuses, subject to caller access, other filters, and pagination. "
                "There is no default status filter or ALL status value. "
            )
        ),
    ] = Query(
        None,
        description=(
            "Optional exact-status filter. When omitted, includes jobs in all "
            "statuses, subject to caller access, other filters, and pagination. "
            "There is no default status filter or ALL status value. "
        ),
        alias="status",
    ),
    queue_name: Annotated[
        StrictStr | None,
        Field(description="Filter by queue name recorded in training submission metadata."),
    ] = Query(
        None,
        description="Filter by queue name recorded in training submission metadata.",
        alias="queue_name",
    ),
    limit: Annotated[int, Field(strict=True, ge=1)] | None = Query(
        20, description="", alias="limit", ge=1
    ),
    page_token: Annotated[
        StrictStr | None,
        Field(
            description=(
                "Opaque continuation token for the same project and filters. The token "
                "never grants access; every request rechecks caller permissions. "
            )
        ),
    ] = Query(
        None,
        description=(
            "Opaque continuation token for the same project and filters. The token "
            "never grants access; every request rechecks caller permissions. "
        ),
        alias="page_token",
    ),
    token_OpenShiftBearer: TokenModel = Security(get_token_OpenShiftBearer),
) -> ListTrainingJobs200Response:
    """List training jobs in an OpenShift Project"""
    if not BaseTrainingJobsApi.subclasses:
        raise ApiError(501, "not_implemented", "This operation is not implemented in the scaffold.")
    return await BaseTrainingJobsApi.subclasses[0]().list_training_jobs(
        project,
        status,
        queue_name,
        limit,
        page_token,
        token_OpenShiftBearer=token_OpenShiftBearer,
    )


@router.post(
    "/projects/{project}/training-jobs",
    responses={
        202: {
            "model": TrainingJobSubmission,
            "description": "RayJob created; training execution proceeds asynchronously",
        },
        400: {
            "model": ErrorResponse,
            "description": "Malformed JSON or invalid query/path parameter syntax",
        },
        401: {
            "model": ErrorResponse,
            "description": "Missing, invalid, or expired OpenShift bearer token",
        },
        403: {
            "model": ErrorResponse,
            "description": (
                "User lacks OpenShift RBAC permissions for the requested resource or project"
            ),
        },
        404: {
            "model": ErrorResponse,
            "description": (
                "Target project, RayJob, or referenced project resource does not exist "
                "in the requested scope"
            ),
        },
        409: {
            "model": ErrorResponse,
            "description": "A RayJob with the requested name already exists in the project",
        },
        415: {"model": ErrorResponse, "description": "Request body must use application/json"},
        422: {
            "model": ErrorResponse,
            "description": "JSON is well-formed but fails schema or domain validation",
        },
        501: {
            "model": ErrorResponse,
            "description": "Requested backend is not implemented in this Developer Preview",
        },
    },
    tags=["Training Jobs"],
    summary="Submit a Ray training job in an OpenShift Project",
    response_model_by_alias=True,
    response_model_exclude_unset=True,
)
async def create_training_job(
    project: Annotated[
        StrictStr,
        Field(
            description=(
                "Explicit pre-existing OpenShift Project (Kubernetes namespace); all "
                "resource references are scoped to it. Provision the project through "
                "normal OpenShift self-service or administrator workflows before using "
                "this API. The Training API does not create projects or namespaces and "
                "never falls back to a default namespace or an elevated service "
                "identity. A missing project returns 404; insufficient caller "
                "permissions return 403. "
            )
        ),
    ] = Path(
        ...,
        description=(
            "Explicit pre-existing OpenShift Project (Kubernetes namespace); all "
            "resource references are scoped to it. Provision the project through "
            "normal OpenShift self-service or administrator workflows before using "
            "this API. The Training API does not create projects or namespaces and "
            "never falls back to a default namespace or an elevated service "
            "identity. A missing project returns 404; insufficient caller "
            "permissions return 403. "
        ),
        examples=["team-alpha-ml"],
    ),
    create_job_request: CreateJobRequest = Body(
        ...,
        description="",
        examples=[
            {
                "name": "llama3-8b-alpaca-lora",
                "queue_name": "team-alpha-local-queue",
                "backend": "ray",
                "model": {"uri": "hf://hf-secret-token/meta-llama/Llama-3.2-3B"},
                "dataset": {"uri": "hf://hf-secret-token/tatsu-lab/alpaca"},
                "algorithm": {
                    "name": "lora_sft",
                    "parameters": {
                        "learning_rate": 2.0e-5,
                        "num_epochs": 3,
                        "effective_batch_size": 8,
                        "max_seq_len": 2048,
                    },
                },
                "resources": {
                    "num_nodes": 2,
                    "gpus_per_node": 4,
                    "gpu_type": "nvidia.com/gpu",
                    "cpus_per_node": "16",
                    "memory_per_node": "64Gi",
                },
                "output": {
                    "destination_uri": "s3://checkpoint-storage/my-ml-bucket/checkpoints/llama3-lora/"
                },
            }
        ],
    ),
    token_OpenShiftBearer: TokenModel = Security(get_token_OpenShiftBearer),
) -> TrainingJobSubmission:
    """Submit a Ray training job in an OpenShift Project"""
    if not BaseTrainingJobsApi.subclasses:
        raise ApiError(501, "not_implemented", "This operation is not implemented in the scaffold.")
    return await BaseTrainingJobsApi.subclasses[0]().create_training_job(
        project,
        create_job_request,
        token_OpenShiftBearer=token_OpenShiftBearer,
    )


@router.get(
    "/projects/{project}/training-jobs/{job_id}",
    responses={
        200: {
            "model": TrainingJob,
            "description": (
                "Accepted submission configuration, current RayJob status, and all "
                "available job details"
            ),
        },
        401: {
            "model": ErrorResponse,
            "description": "Missing, invalid, or expired OpenShift bearer token",
        },
        403: {
            "model": ErrorResponse,
            "description": (
                "User lacks OpenShift RBAC permissions for the requested resource or project"
            ),
        },
        404: {
            "model": ErrorResponse,
            "description": (
                "Target project, RayJob, or referenced project resource does not exist "
                "in the requested scope"
            ),
        },
    },
    tags=["Training Jobs"],
    summary="Get training job status and available details",
    response_model_by_alias=True,
    response_model_exclude_unset=True,
)
async def get_training_job(
    project: Annotated[
        StrictStr,
        Field(
            description=(
                "Explicit pre-existing OpenShift Project (Kubernetes namespace); all "
                "resource references are scoped to it. Provision the project through "
                "normal OpenShift self-service or administrator workflows before using "
                "this API. The Training API does not create projects or namespaces and "
                "never falls back to a default namespace or an elevated service "
                "identity. A missing project returns 404; insufficient caller "
                "permissions return 403. "
            )
        ),
    ] = Path(
        ...,
        description=(
            "Explicit pre-existing OpenShift Project (Kubernetes namespace); all "
            "resource references are scoped to it. Provision the project through "
            "normal OpenShift self-service or administrator workflows before using "
            "this API. The Training API does not create projects or namespaces and "
            "never falls back to a default namespace or an elevated service "
            "identity. A missing project returns 404; insufficient caller "
            "permissions return 403. "
        ),
        examples=["team-alpha-ml"],
    ),
    job_id: Annotated[
        StrictStr,
        Field(
            description=(
                "Name of the RayJob custom resource, scoped to the target project. "
                "Resolve it only through caller-authorized Kubernetes APIs in that "
                "project. "
            )
        ),
    ] = Path(
        ...,
        description=(
            "Name of the RayJob custom resource, scoped to the target project. "
            "Resolve it only through caller-authorized Kubernetes APIs in that "
            "project. "
        ),
        examples=["llama3-8b-alpaca-lora"],
    ),
    token_OpenShiftBearer: TokenModel = Security(get_token_OpenShiftBearer),
) -> TrainingJob:
    """Get training job status and available details"""
    if not BaseTrainingJobsApi.subclasses:
        raise ApiError(501, "not_implemented", "This operation is not implemented in the scaffold.")
    return await BaseTrainingJobsApi.subclasses[0]().get_training_job(
        project,
        job_id,
        token_OpenShiftBearer=token_OpenShiftBearer,
    )


@router.delete(
    "/projects/{project}/training-jobs/{job_id}",
    responses={
        204: {
            "description": (
                "Terminal RayJob deleted; KubeRay applies its configured owned-resource cleanup"
            )
        },
        400: {
            "model": ErrorResponse,
            "description": "Malformed JSON or invalid query/path parameter syntax",
        },
        401: {
            "model": ErrorResponse,
            "description": "Missing, invalid, or expired OpenShift bearer token",
        },
        403: {
            "model": ErrorResponse,
            "description": (
                "User lacks OpenShift RBAC permissions for the requested resource or project"
            ),
        },
        404: {
            "model": ErrorResponse,
            "description": (
                "Target project, RayJob, or referenced project resource does not exist "
                "in the requested scope"
            ),
        },
        409: {
            "model": ErrorResponse,
            "description": "RayJob is not terminal and cannot be deleted",
        },
    },
    tags=["Training Jobs"],
    summary="Delete a terminal Ray training job record",
    response_model_by_alias=True,
    response_model_exclude_unset=True,
)
async def delete_training_job(
    project: Annotated[
        StrictStr,
        Field(
            description=(
                "Explicit pre-existing OpenShift Project (Kubernetes namespace); all "
                "resource references are scoped to it. Provision the project through "
                "normal OpenShift self-service or administrator workflows before using "
                "this API. The Training API does not create projects or namespaces and "
                "never falls back to a default namespace or an elevated service "
                "identity. A missing project returns 404; insufficient caller "
                "permissions return 403. "
            )
        ),
    ] = Path(
        ...,
        description=(
            "Explicit pre-existing OpenShift Project (Kubernetes namespace); all "
            "resource references are scoped to it. Provision the project through "
            "normal OpenShift self-service or administrator workflows before using "
            "this API. The Training API does not create projects or namespaces and "
            "never falls back to a default namespace or an elevated service "
            "identity. A missing project returns 404; insufficient caller "
            "permissions return 403. "
        ),
        examples=["team-alpha-ml"],
    ),
    job_id: Annotated[
        StrictStr,
        Field(
            description=(
                "Name of the RayJob custom resource, scoped to the target project. "
                "Resolve it only through caller-authorized Kubernetes APIs in that "
                "project. "
            )
        ),
    ] = Path(
        ...,
        description=(
            "Name of the RayJob custom resource, scoped to the target project. "
            "Resolve it only through caller-authorized Kubernetes APIs in that "
            "project. "
        ),
        examples=["llama3-8b-alpaca-lora"],
    ),
    token_OpenShiftBearer: TokenModel = Security(get_token_OpenShiftBearer),
) -> None:
    """Delete a terminal Ray training job record"""
    if not BaseTrainingJobsApi.subclasses:
        raise ApiError(501, "not_implemented", "This operation is not implemented in the scaffold.")
    return await BaseTrainingJobsApi.subclasses[0]().delete_training_job(
        project,
        job_id,
        token_OpenShiftBearer=token_OpenShiftBearer,
    )
